name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - run: echo 'agex.gkzhb.tk' > public/CNAME
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
